version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app"
      - "dev-static-data:/vol/web"
    command:
      sh -c "python manage.py waitfordb &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgresdb
      - DATABASE_USER=postgresuser 
      - DATABASE_PASS=postgrespass
    depends_on:
      - db
    
  db:
    image: postgres:16rc1-alpine3.18
    volumes: 
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgresuser 
      - POSTGRES_PASSWORD=postgrespass



volumes:
  db-data:
  dev-static-data:


